site_name: Vrindavan

theme:
  name: material
  icon:
    logo: material/sprout
    favicon: material/sprout
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
