site_name: Vrindavan API

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
